# Generated by Django 3.1.2 on 2020-10-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='existing',
            field=models.BooleanField(default=True, verbose_name='موجود'),
        ),
    ]
