# Generated by Django 3.1.2 on 2020-10-09 13:26

from django.db import migrations, models
import eshop_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0003_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to=eshop_product.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
