# Generated by Django 3.1.2 on 2020-10-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=150, verbose_name='عنوان سایت')),
                ('address', models.CharField(max_length=150, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=150, verbose_name='تلفن')),
                ('mobile', models.CharField(max_length=150, verbose_name='موبایل')),
                ('fax', models.CharField(max_length=150, verbose_name='فکس')),
                ('email', models.CharField(max_length=150, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'مدیریت سایت',
            },
        ),
    ]
