# Generated by Django 4.1.6 on 2023-03-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_wish_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish_list',
            options={'verbose_name': 'لیست علاقه مندی ها', 'verbose_name_plural': 'لیست علاقه مندی ها'},
        ),
    ]
