# Generated by Django 4.1.6 on 2023-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0002_auto_20201013_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=150, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=200, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(null=True, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=200, null=True, verbose_name='عموان پیام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(null=True, verbose_name='متن پیام'),
        ),
    ]
