# Generated by Django 4.1.6 on 2023-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0003_alter_contactus_email_alter_contactus_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, null=True, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'ایمیل کاربران',
                'verbose_name_plural': 'ایمیل کاربران',
            },
        ),
    ]
