# Generated by Django 4.2.1 on 2024-02-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0004_emailnews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnews',
            options={'verbose_name': 'ایمیل کاربرانن', 'verbose_name_plural': 'ایمیل کاربران'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_readd',
            field=models.BooleanField(null=True, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=210, null=True, verbose_name='عموان پیام'),
        ),
    ]
