# Generated by Django 4.2.1 on 2024-02-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0005_alter_emailnews_options_contactus_is_readd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='is_readd',
        ),
    ]
