# Generated by Django 3.1.2 on 2020-10-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refID',
            field=models.IntegerField(default=0, verbose_name='کد پیگیری'),
            preserve_default=False,
        ),
    ]
